# Filename: labs/01-without-helm/ingress.yaml
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: guestbook-ingress

spec:
  # Host rules
  rules:
    - host: frontend.minikube.local
      http:
        # Collection of paths that map requests to backends
        paths:
          - path: /
            # Define the referenced service endpoint
            # to which the traffic will be forwarded to
            backend:
              serviceName: frontend
              servicePort: 80

    - host: backend.minikube.local
      http:
        paths:
          - path: /
            backend:
              serviceName: backend
              servicePort: 80
