apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend
  name: backend
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app: backend
 # type: NodePort
