---
# Source: 02-developing-templates/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-02-developing-templates
  labels:
    helm.sh/chart: 02-developing-templates-0.1.0
    app.kubernetes.io/name: 02-developing-templates
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: 02-developing-templates
    app.kubernetes.io/instance: RELEASE-NAME
