---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hollow-app
  name: hollow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hollow-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hollow-app
    spec:
      containers:
        - name: hollow-app
          image: eshanks16/k8s-hollowapp:v5
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              value: "my-secret-key"
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: hollow-config
                  key: db.string
