---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: hollow-ingress
  labels:
    app: hollow-app

spec:
  # Host rules
  rules:
    - host: frontend.minikube.local
      http:
        # Collection of paths that map requests to backends
        paths:
          - path: /
            # Define the referenced service endpoint
            # to which the traffic will be forwarded to
            backend:
              serviceName: hollow-app
              servicePort: 5000
