---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: mysql-volume

spec:
  storageClassName: manual

  capacity:
    storage: 10Gi

  accessModes:
    # ReadWriteOnce: the volume can be mounted as read-write by a single node
    # ReadWriteMany: the volume can be mounted as read-write by many nodes
    # ReadOnlyMany: the volume can be mounted read-only by many nodes
    - ReadWriteOnce

  # Mount a file or directory from the host node's filesystem into our Pod
  hostPath:
    path: "/mnt/data"
