---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mariadb-deployment
  labels:
    app: mariadb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb

  template:
    metadata:
      labels:
        app: mariadb

    spec:
      containers:
        - name: mariadb
          image: docker.io/mariadb:10.4

          # Add the "Secrets" (or "ConfigMaps") as environment variables
          # A list, define one by one
          env:
            # Name of the environment variable that is added to the container
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Or using "configMapRef" for a "ConfigMap"
                  name: mariadb-root-password
                  key: password

          # Set environment variables from
          # all key-value pairs of a "Secret" or "ConfigMap"
          envFrom:
            # Use the "key name" as the "environment variable name"
            # and the "key value" as the "environment variable value"
            - secretRef:
                # In this case,
                # set the "MYSQL_USER" and "MYSQL_PASSWORD"
                # from the "mariadb-user-creds" Secret
                name: mariadb-user-creds

          ports:
            - containerPort: 3306
              protocol: TCP

          # The "volumeMounts" is pretty self-explanatory
          volumeMounts:
            # On most distribution's version of MySQL,
            # the data directory is located in the /var/lib/mysql/ directory.
            - name: mariadb-data-volume
              mountPath: /var/lib/mysql

              # Create a volume mount for the mariadb-config-volume
              # (specified in the volumes list below it)
              # to the path /etc/mysql/conf.d
            - name: mariadb-config-volume
              mountPath: /etc/mysql/conf.d

      # Both "Secrets" and "ConfigMaps" can be
      # the source of Kubernetes "volumes"
      # and mounted into the containers
      volumes:
        # An emptyDir (effectively a temporary or ephemeral)
        # volume mounted to "/var/lib/mysql" to store the MariaDB data
        # Note: when the Pod restarts, the data in the emptyDir volume is lost
        - name: mariadb-data-volume
          emptyDir: {}

        # Add our "ConfigMap" as a source
        - name: mariadb-config-volume
          configMap:
            name: mariadb-config
            items:
              - key: max_allowed_packet.cnf
                path: max_allowed_packet.cnf
