---
apiVersion: v1
kind: Secret

metadata:
  name: mariadb-root-password

type: Opaque

# Define key-value pairs here
# "Secrets" (or "ConfigMaps") can hold more than one pair
data:
  # "Secrets" are stored base64-encoded, so they are not wildly secure

  # $ echo -n 'KubernetesRocks!' | base64
  # - n: not print the trailing newline character
  password: S3ViZXJuZXRlc1JvY2tzIQ==
