---
apiVersion: v1
kind: Secret

metadata:
  name: mariadb-root-password

type: Opaque
data:
  # echo -n 'KubernetesRocks!' | base64
  # n: not print the trailing newline character
  password: S3ViZXJuZXRlc1JvY2tzIQ==
