---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: devs-read-pods
  namespace: test

subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: devs

roleRef:
  name: pod-access
  kind: Role

  apiGroup: rbac.authorization.k8s.io
