# Filename: labs/01-without-helm/mongodb-pv.yaml
---
kind: PersistentVolume
apiVersion: v1

metadata:
  name: mongodb-pv
  labels:
    type: local

spec:
  storageClassName: manual

  capacity:
    storage: 100Mi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: /mnt/data
