{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "study.serviceAccountName" . }}
  labels:
{{ include "study.labels" . | nindent 4 }}
{{- end -}}
