---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole

metadata:
  name: helm-tiller-access

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "create"]
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
#
# metadata:
#   name: tiller-role
#   namespace: lab
#
# rules:
#   - apiGroups: ["", "extensions", "apps"]
#     resources: ["*"]
#     verbs: ["*"]
#   - apiGroups: ["batch"]
#     resources:
#       - jobs
#       - cronjobs
#     verbs: ["*"]
