---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: tiller-access
  namespace: kube-system

# https://v2.helm.sh/docs/rbac/#example-deploy-helm-in-a-namespace-talking-to-tiller-in-another-namespace

rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments", "services"]
    verbs: ["get", "list", "create", "delete"]

  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete"]
