---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: tiller-manager
  namespace: kube-system

rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments", "services"]
    verbs: ["get", "list", "create", "delete"]

  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete"]
