---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: tiller-access
  namespace: kube-system

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
#  - apiGroups: ["", "apps"]
#    resources: ["pods", "deployments", "services"]
#    verbs: ["get", "list", "create", "update"]

#  - apiGroups: [""]
#    resources: ["pods/portforward"]
#    verbs: ["create"]
# metadata:
#   name: tiller-role
#   namespace: lab
#
# rules:
#   - apiGroups: ["", "extensions", "apps"]
#     resources: ["*"]
#     verbs: ["*"]
#   - apiGroups: ["batch"]
#     resources:
#       - jobs
#       - cronjobs
#     verbs: ["*"]
