---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: tiller-manager
  namespace: kube-system

rules:
  - apiGroups: ["", "batch", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
