---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: harrison-use-tiller

subjects:
  - kind: User
    # Name is case sensitive
    name: harrison
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: ClusterRole
  name: helm-tiller-access
  apiGroup: rbac.authorization.k8s.io
