# An API token will be automatically created and stored in the cluster
# Can be used in RoleBinding and ClusterRoleBinding as subjects
# ServiceAccounts are used in Pod/RS/Deployment declarations
---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: tiller-sa
  namespace: kube-system
