# ServiceAccounts are used in Pod/ReplicaSet/Deployment declarations
# It can be used in RoleBinding and ClusterRoleBinding as Subjects
---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: tiller-sa
  namespace: kube-system
