---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: tiller-rolebinding

subjects:
  # or remove apiGroup?
  # can achieve the same result?
  - apiGroup: rbac.authorization.k8s.io
    kind: ServiceAccount
    name: tiller-sa
    namespace: kube-system

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # The cluster-admin ClusterRole exists by default in your Kubernetes cluster,
  # and allows super-user operations in all of the cluster resources
  name: cluster-admin
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
#
# metadata:
#   name: tiller-role-binding
#   namespace: lab
#
# subjects:
#   - kind: ServiceAccount
#     name: tiller
#     namespace: lab
# roleRef:
#   kind: Role
#   name: tiller-role
#   apiGroup: rbac.authorization.k8s.io
