---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: tiller-manager

rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: tiller-manager
  namespace: kube-system

rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: tiller-manager
  namespace: test

rules:
  - apiGroups: ["", "batch", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
