---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: tiller-binding
  namespace: test

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller-role

subjects:
  - kind: ServiceAccount
    name: tiller-sa
    namespace: kube-system
