---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: tiller-manager-binding
  namespace: kube-system

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller-manager

subjects:
  - kind: ServiceAccount
    name: tiller-sa
    namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: tiller-manager-binding
  namespace: test

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller-manager

subjects:
  - kind: ServiceAccount
    name: tiller-sa
    namespace: kube-system
