apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
data:
  guestbook-name: {{ .Values.config.guestbook_name }}
  backend-uri: {{ .Values.config.backend_uri }}
