---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: salme-ns-admin
  namespace: test

subjects:
  - kind: User
    # Name is case sensitive
    name: jsalmeron
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ns-admin
  apiGroup: rbac.authorization.k8s.io
