kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: salme-ns-admin
  namespace: test
subjects:
- kind: User
  name: jsalmeron # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ns-admin
  apiGroup: rbac.authorization.k8s.io
