---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: salme-reads-all-pods

subjects:
  - kind: User
    # Name is case sensitive
    name: jsalmeron
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: ClusterRole
  name: all-pod-access
  apiGroup: rbac.authorization.k8s.io
