---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: salme-use-tiller
subjects:
  - kind: User
    # Name is case sensitive
    name: jsalmeron
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: helm-tiller-access
  apiGroup: rbac.authorization.k8s.io
