kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: salme-use-tiller
subjects:
- kind: User
  name: jsalmeron # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: helm-tiller-access
  apiGroup: rbac.authorization.k8s.io
