dependencies:
  - name: backend
    version: ~1.2.2
    repository: http://127.0.0.1:8879/charts
    condition: backend.enabled,global.backend.enabled
    tags:
      - api
  - name: frontend
    version: ^1.2.0
    repository: http://127.0.0.1:8879/charts
  - name: database
    version: ~1.2.2
    repository: http://127.0.0.1:8879/charts
    condition: database.enabled,global.database.enabled
    tags:
      - api



