dependencies:
  - name: backend
    version: ~1.2.2
    repository: http://127.0.0.1:8879/charts
    condition: backend.enabled,global.backend.enabled
    tags:
      - api
  - name: frontend
    version: ^1.2.0
    repository: http://127.0.0.1:8879/charts
  - name: mongodb
    version: 6.1.x
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: mongodb.enabled
    tags:
      - api



