---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: devs-read-pods
  namespace: test

subjects:
  - kind: Group
    # Name is case sensitive
    name: devs
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: pod-access
  apiGroup: rbac.authorization.k8s.io
