---
apiVersion: v1
kind: Pod

metadata:
  name: default-pod

spec:
  containers:
    # Alpine Linux is built around "musl libc" and "BusyBox"
    # It has access to a package repository
    # that is much more complete than other "BusyBox" based images
    - name: alpine
      image: alpine:3.10

      # To keep the container running
      command:
        - "sleep"
        - "10000"

      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "apk update; apk add bash; apk add curl"]
# apk (Alpine Package Keeper)
# - update: update the index of available packages
# - add: add new packages or upgrade packages to the running system

# sh calls the program sh as interpreter and
# the -c flag means execute the following command
# as interpreted by this program.
# In Ubuntu,
# sh is usually symlinked to /bin/dash,
# meaning that if you execute a command with sh -c the
# dash shell will be used to
# execute the command instead of bash.
# The shell called with sh depends on the symlink -
# you can find out with readlink -e $(which sh).
# You should use sh -c when you want to execute a command
# specifically with that shell instead of bash.
