---
apiVersion: v1
kind: Pod

metadata:
  name: demo-pod

spec:
  serviceAccountName: demo-sa
  containers:
    - name: alpine
      image: alpine:3.10
      command:
        - "sleep"
        - "10000"
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "apk update; apk add bash; apk add curl"]
