---
apiVersion: v1
kind: Pod

metadata:
  name: default-pod

spec:
  containers:
    # Alpine Linux is a Linux distribution built around musl libc and BusyBox
    # The image is only 5 MB in size and has access to a package repository
    # that is much more complete than other BusyBox based images
    # This makes Alpine Linux a great image base for utilities
    # and even production applications
    # Read more about Alpine Linux here and
    # you can see how their mantra fits in right at home with Docker images
    - name: alpine
      image: alpine:3.10
      command:
        - "sleep"
        - "10000"
#      lifecycle:
#        postStart:
#          exec:
#            command:
#              ["/bin/sh", "-c", "apk update", "apk add bash", "apk add curl"]
#            command: ["/bin/sh","-c"]
#            args: ["command one; command two; command three"]
# apk update
# apk upgrade
# apk add bash

# sh calls the program sh as interpreter and
# the -c flag means execute the following command
# as interpreted by this program.
# In Ubuntu,
# sh is usually symlinked to /bin/dash,
# meaning that if you execute a command with sh -c the
# dash shell will be used to
# execute the command instead of bash.
# The shell called with sh depends on the symlink -
# you can find out with readlink -e $(which sh).
# You should use sh -c when you want to execute a command
# specifically with that shell instead of bash.
