---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: demo-reads-pods
  namespace: default

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-access

subjects:
  - kind: ServiceAccount
    name: demo-sa
    namespace: default
