---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: pod-access
  namespace: default

rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
