---
apiVersion: v1
kind: Pod

metadata:
  name: pod-demo-sa

spec:
  serviceAccountName: demo-sa
  containers:
    - name: alpine
      image: alpine:3.9
      command:
        - "sleep"
        - "10000"
        -
